### ISSUE TITLE
Please release 0.9.1

### ISSUE THREAD

**Issue by foxx1337** [SFTtech/sftdyn#11]
... with at least f6b1d5d so that I can properly `pip install` it without "source".

**Comment by foxx1337** [comment]
I'm running sftdyn behind an nginx and the real IP is always in the header.

**Comment by TheJJ** [comment]
Okay, will do :)

**Comment by TheJJ** [comment]
done: 92cf98c24b75306af7e33db4a810a96520d70940 :)
