### ISSUE TITLE
Draft pad: https://pad.stusta.de/p/openage-gamestate

### ISSUE THREAD

**Issue by abowassm** [SFTtech/sftdyn#12]
Draft pad: https://pad.stusta.de/p/openage-gamestate

_Originally posted by @TheJJ in https://github.com/SFTtech/openage/issues/964#issuecomment-360605942_

**Comment by mallardduck** [comment]
Wrong repo...this doesn't seem to relate to DynDNS

**Comment by TheJJ** [comment]
Yes, you seem to have confused our repos :) Closing.
