### ISSUE TITLE
Multiple zones for multiple domains

### ISSUE THREAD

**Issue by zenny** [SFTtech/sftdyn#14]
Hi,

Thanks for sharing this code. 

However, is it possible to host multiple zones? 

I meant how  to handle if there are multiple domains which point to different servers, like:

domain1.tld > remote1.dynamichost (1st remote server with dynamic ip)
domain2.tld > remote1.dynamichost (1st remote server with dynamic ip)
domain3.tld > remote2.dynamichost (2nd remote server with dynamic ip)
domain4.tld > remote3.dynamichost (3rd remote server with dynamic ip)
domain5.tld > remote3.dyanmichost (3rd remote server with dynamic ip)

Here, dynamic ip = dynamic public IP

without using subdomains?

Cheers,
/z

**Comment by TheJJ** [comment]
Just from your question, yes that is possible. But I don't understand what you want to achieve.

Do you want to dynamically update IPs in multiple zones depending on the client ID?
Can you give a more concrete example please? :)

**Comment by zenny** [comment]
> Just from your question, yes that is possible. But I don't understand what you want to achieve.
> 
> Do you want to dynamically update IPs in multiple zones depending on the client ID?
> Can you give a more concrete example please? :)

@TheJJ, thanks.

To make things clear, let me state that, I would like host sites in servers with dynamic public IPs (without static public IP) including TLDs and their subdomains, if any. Can that be done with this script, deployed in two different BIND servers with static IPs in different locations? 

Technically, I meant host two BIND servers with your script in two separate locations with static public IP for redundancy which shall point to web services hosted in different web servers hosting multiple domains in different locations with dynamic public IPs.

Any clue appreciated!

Cheers and season's greetings.
/z

**Comment by TheJJ** [comment]
I'm still not 100% clear, sorry :)
I guess you want to update the names of multiple domains like `yourmom.org` and `yourdad.net` with a single sftdyn instance, so that they point to some server name such that:

```
yourmom.org -> dynip1
yourdad.net -> dynip2
yourcat.lol -> dynip1
```

When `dynip1` is updated, you would update `yourmom.org` and `yourcat.lol`, is that right?

Because `yourmom.org` and `yourcat.lol` are hosted on two different BIND servers, you want to send the update to the corresponding BIND.

Yes that is possible with sftdyn. Basically you have to modify the `nsupdatecommand` so it uses a specific tsig-key, and then depending on the client id, contact the "right" bind.

I'd suggest another setup, though: Have one bind be master for all the zones, and the other bind slave for all the zones. That way you update all of them on the master, and the slave just replicates all the data. When the master is down, the zones just stay alive. Dynamic IP updates are always done on the master so it has to be up and running to accept updates.

Does that help?

**Comment by zenny** [comment]
> I'm still not 100% clear, sorry :)
> I guess you want to update the names of multiple domains like `yourmom.org` and `yourdad.net` with a single sftdyn instance, so that they point to some server name such that:
> 
> ```
> yourmom.org -> dynip1
> yourdad.net -> dynip2
> yourcat.lol -> dynip1
> ```
> 
> When `dynip1` is updated, you would update `yourmom.org` and `yourcat.lol`, is that right?
> 
> Because `yourmom.org` and `yourcat.lol` are hosted on two different BIND servers, you want to send the update to the corresponding BIND.
> 
> Yes that is possible with sftdyn. Basically you have to modify the `nsupdatecommand` so it uses a specific tsig-key, and then depending on the client id, contact the "right" bind.
> 
> I'd suggest another setup, though: Have one bind be master for all the zones, and the other bind slave for all the zones. That way you update all of them on the master, and the slave just replicates all the data. When the master is down, the zones just stay alive. Dynamic IP updates are always done on the master so it has to be up and running to accept updates.
> 
> Does that help?

@TheJJ Thanks for extremely helpful pointers and your time.

Let me clarify a bit.

1. The bind servers are hosted in two different VPSes in two different locations with static public IPs.

2. You are exactly right that the domains (yourmom.com, yourdad.org, yourcat.lol) are to be pointed to different webservers with dynamic public IPs in locations difgerent than the Bind9 instances.

3. The only bottleneck is the updating of the IP once the dynamic IP changes in the downstream webservers.

4. The problem is how can one update the new IP in nameservers with an automagical script once the dynamic IP changes?

5. You mentioned about changing 'nsupdate' command, any pointer to make it happen with sftdns? 

You indeed have a good writing skill. A gist contribution to this direction will be highly apreciated.

Cheers,
/z

**Comment by TheJJ** [comment]
Sorry for the delay :)
If it is clear what dynamic update affects what BIND instance, you could just run one sftdyn instance on each BIND instance. Then each sftdyn updates the BIND running on the same VPS and your use-case should be covered.

The other solution I think you would benefit from is to host all domains on all VPS with BIND: One is the master, the others are slaves. On the master instance, sftdyn is running, and can update the IPs for all the zones. The slaves are then updated automatically and you have redundancy for all your zones in case one of the VPS is down for maintenance or broken, ...

You don't need to adjust the `nsupdate` command for both solutions. If you need further assistance, I can try to add this feature to sftdyn so it can be more easily used without having to do some programming.

**Comment by zenny** [comment]
> Sorry for the delay :)

@TheJJ, Never mind, thanks for your useful inputs even during holidays. Highly appreciated!

> If it is clear what dynamic update affects what BIND instance, you could just run one sftdyn instance on each BIND instance. Then each sftdyn updates the BIND running on the same VPS and your use-case should be covered.

Do you mean without making any master or slave? In that case, the deployment scenario differs from the one in Readme.md file, I guess.

> 
> The other solution I think you would benefit from is to host all domains on all VPS with BIND: One is the master, the others are slaves. On the master instance, sftdyn is running, and can update the IPs for all the zones. The slaves are then updated automatically and you have redundancy for all your zones in case one of the VPS is down for maintenance or broken, ...

Some deployment inputs will be appreciated as it differs from the original scenario of sftdyn.
> 
> You don't need to adjust the `nsupdate` command for both solutions. If you need further assistance, I can try to add this feature to sftdyn so it can be more easily used without having to do some programming.

The latter shall be very appreciated if you can add a feature like creating two nameservers (for redundancy, say ns1.nameserver.com and ns2.nameserver.com in VPSes with static public IPs whose dns records can get updated automagically from the services running in remote hosts with dyanmic IPs with an additional script to sftdyn. Thanks again and happy holidays,

Cheers,
/z

**Comment by TheJJ** [comment]
> > Sorry for the delay :)
> 
> @TheJJ, Never mind, thanks for your useful inputs even during holidays. Highly appreciated!
> 
> > If it is clear what dynamic update affects what BIND instance, you could just run one sftdyn instance on each BIND instance. Then each sftdyn updates the BIND running on the same VPS and your use-case should be covered.
> 
> Do you mean without making any master or slave? In that case, the deployment scenario differs from the one in Readme.md file, I guess.

Yes, that would be one VPS with a BIND and sftdyn, responsible for some subset of your domains. The same setup for a different subset of domains would be on another VPS. For each of those VPSs, the deployment scenario is the one from the README.

> > The other solution I think you would benefit from is to host all domains on all VPS with BIND: One is the master, the others are slaves. On the master instance, sftdyn is running, and can update the IPs for all the zones. The slaves are then updated automatically and you have redundancy for all your zones in case one of the VPS is down for maintenance or broken, ...
> 
> Some deployment inputs will be appreciated as it differs from the original scenario of sftdyn.

The sftdyn deployment is also the regular one. What differs is the BIND setup: You have to add a slave instance and let the slave receive updates from the master. The master instance is the one that is updated by sftdyn. So basically you have the default setup, plus the [setup of a slave](http://www.microhowto.info/howto/configure_bind_as_a_slave_dns_server.html).

> 
> > You don't need to adjust the `nsupdate` command for both solutions. If you need further assistance, I can try to add this feature to sftdyn so it can be more easily used without having to do some programming.
> 
> The latter shall be very appreciated if you can add a feature like creating two nameservers (for redundancy, say ns1.nameserver.com and ns2.nameserver.com in VPSes with static public IPs whose dns records can get updated automagically from the services running in remote hosts with dyanmic IPs with an additional script to sftdyn. Thanks again and happy holidays,

Creating two nameservers for redundancy doesn't need additional features in sftdyn, this is done with the regular master-slave setup. Unless I misunderstood you.

**Comment by TheJJ** [comment]
I'll close this now, please just ask if you need further help (or come by in the chatroom #sfttech:matrix.org)
