### ISSUE TITLE
Any info on binding IP:Port instead of just IP

### ISSUE THREAD

**Issue by saurabhgayali** [SFTtech/sftdyn#20]
Want to host multiple website on my dynamic IP using ports. but documentation is unclear on the issue.

**Comment by TheJJ** [comment]
Just to be clear - you want to run multiple SFTdyn instances on one server with one IP, but on different ports?

Does this mean you also control different `bind` servers? Or what is your concrete use-case?

**Comment by saurabhgayali** [comment]
I have two domains. I have one IP. I am running Windows.

**Comment by TheJJ** [comment]
Are your domains already working and are hosted on your BIND?
Do you want to assign your dynamic hosts simultaneously to two domains?

You have to explain your desired setup a bit more so we can help you.

**Comment by saurabhgayali** [comment]
I had one domain but my hosting plan has expired. I am also planning to make another website and purchasing the domain. 
But instead of buying a shared hosting plan which will give me PHP/MySQL only I am planning to host on my PC with PHP and Python both.

My ISP has given my Dynamic IP and Static IP will cost me extra. Further my scraping activity may cause me future banning from websites. Therefore I need to have dynamic IP and Different local servers hosted on different folders. I was able to do this with no-ip but it is not again free for own top level domain. 

So summarizing. One domain is already working. Another I will purchase and it will be working.

**Comment by TheJJ** [comment]
Alright. So the first step would be hosting your zone with bind, so sftdyn can then update the records. To host your zone (i.e. have a DNS nameserver) you need a static IP - otherwise the dynamic hosts have to contact another dynamic host to set their IP in the zone. After your zone is up and running, you can use sftdyn so the dynamic hosts can update their A records in the zone via http.

**Comment by TheJJ** [comment]
Do you need further assistance? If yes, please just write in this issue or join our chat.
