### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by darkdragon-001** [SFTtech/sftdyn#3]
As far as I see `aiohttp` supports IPv6 without any additional modifications.

When I didn't overlook something, this should only involve modifications in `args.py`
* `stringtoipport()`: Parse IPv6 address similar to browsers `[xxxx:x::xxxx]:PORT`
* `--nsupdatecommand`: Update the `AAAA` record

Would be nice to support both at the same time. This would involve a switch in `Server::handle_request()` based on `ip`.

**Comment by TheJJ** [comment]
With a sudden occurrence of motivation, I implemented this in 34f4cf79cd3955ae0f53c1b5249234588e01917c (and released v0.8) :)
I did it without a switch in `handle_request`, but a function in the config file instead.
