### ISSUE TITLE
SSLContext() should be set

### ISSUE THREAD

**Issue by wickedwout** [SFTtech/sftdyn#4]
The script threw up an error on:
```
self.sslcontext = ssl.SSLContext()
```

missing a protocol.
When I changed it to `self.sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1)` it worked.
Python 3.5.2, openSSL update to the latest version (1.02p I think).

btw: thanks!

**Comment by TheJJ** [comment]
jup, that's a bug. the fix seems easy: https://docs.python.org/3.5/library/ssl.html#ssl.create_default_context

**Comment by TheJJ** [comment]
Fixed with 55575ed170ab206a63cad7430f44902a47edfee3. I missed that bug cause in Python 3.6 the context does the right thing by default.

**Comment by wickedwout** [comment]
👍🏼
