### ISSUE TITLE
[Question] How to make it work like No-ip?

### ISSUE THREAD

**Issue by danimesq** [SFTtech/sftdyn#6]
I'll add this as default program in my OS
How to make it work like No-ip?

**Comment by TheJJ** [comment]
The number one requirement is to have access to a name server that can be updated with a tool like [`nsupdate`](https://linux.die.net/man/8/nsupdate).
Most likely that means that you need to host the zone you want to control yourself, e.g. with [BIND](https://en.wikipedia.org/wiki/BIND).

Apart from that, `sftdyn` works similar to dyn.com and noip.com: a device submits a request to some url, and then a name is updated to the IP of that device.

**Comment by TheJJ** [comment]
If you have another question, please notify us :)
